Homebrew/.github

config.yml

This will auto-close bad/empty issue/PR titles.

config.yml: add request-info configuration.

---

.github/workflows/sync-triage-config.yml

Will defer to @domt4 whether or not this is a good idea/desirable but figured I'd open a PR for discussion.

Sync homebrew-autoupdate

---

.github/workflows/sync-triage-config.yml
.github/workflows/triage-issues.yml

Set `concurrency` on all workflows where it makes sense to do so.

.github/workflows: add more `concurrency`.

---

SUPPORT.md

As per https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project

Add `SUPPORT.md`

---

.github/workflows/sync-triage-config.yml
.github/workflows/triage-issues.yml

Reduce permissions to what is strictly necessary.

workflows: reduce GITHUB_TOKEN permissions

---

.github/workflows/triage-issues.yml

Shamelessly copied @nandahkrishna their hard work in https://github.com/Homebrew/actions/pull/227

triage-issues: update lock parameters

---

SECURITY.md

This should also add a "security" entry to the new issue page for all our repos

Add common SECURITY.md file for the homebrew org

---

.github/workflows/sync-shared-config.yml

Let's add all public repositories in the organisation.

workflows/sync-shared-config: add more repos.

---

.github/actions/sync/shared-config.rb
.rubocop.yml

- better handle missing arguments
- write comment at top of `rubocop.yml`
- don't try to copy files to themselves
- gate GitHub Actions logic to allow local testing

shared-config: more improvements.

---

.github/dependabot.yml

dependabot.yml: add artifacts group.

---

.github/actions/sync/shared-config.rb

The location was previously incorrect.

actions/sync: fix copying of `vale.ini` files.

---

.github/actions/sync/shared-config.rb

This should help fix CI in e.g. https://github.com/Homebrew/governance-private/pull/159 https://github.com/Homebrew/formulae.brew.sh/pull/1243

sync/shared-config: make relative ruby_version/Gemfile* symlinks.

---

.github/workflows/sync-shared-config.yml

workflows/sync-shared-config: fix PR body (again).

---

.github/actions/sync/shared-config.rb

This should push it out in PRs.

sync/shared-config: remove locked threads with Git.

---

.github/workflows/sync-shared-config.yml

Fixes https://github.com/Homebrew/.github/actions/runs/9930371317/job/27429031108#step:12:18.

workflows/sync-shared-config: fix PR creation

---

.github/workflows/stale-issues.yml

Fixes Homebrew/homebrew-core#180127.

workflows/stale-issues: delete branch after closing a stale PR

---

.github/actions/sync/shared-config.rb

actions/sync/shared-config: fix vendor quoting.

---

.github/workflows/stale-issues.yml

stale-issues: set `-xeuo pipefail` globally

---

.github/workflows/sync-shared-config.yml

- set `-xeuo pipefail` globally
- remove unneeded `${{ }}` in `if:` statements
- stagger pull request creation over the next 10 minutes to prevent
errors[^1][^2][^3][^4]
[^1]: https://github.com/Homebrew/.github/actions/runs/11016683882/job/30592792066#step:12:41
[^2]: https://github.com/Homebrew/.github/actions/runs/11016683882/job/30592794353#step:12:41
[^3]: https://github.com/Homebrew/.github/actions/runs/11016683882/job/30592799839#step:12:41
[^4]: https://github.com/Homebrew/.github/actions/runs/11016683882/job/30592802801#step:12:41

sync-shared-config: various improvements

---

.github/workflows/stale-issues.yml

Fixes https://github.com/Homebrew/brew/security/code-scanning/29
Fixes https://github.com/Homebrew/brew/security/code-scanning/30
Fixes https://github.com/Homebrew/brew/security/code-scanning/31

workflows/stale-issues: fix `excessive-permissions` warning

---

.github/workflows/actionlint.yml

https://github.com/Homebrew/.github/pull/210 from a non-fork.

actionlint: suppress zizmor's exit code

---

.github/workflows/actionlint.yml

https://github.com/Homebrew/.github/pull/212 from a non-fork.
Closes https://github.com/Homebrew/.github/pull/212.

feat: pin workflow action sha

---

.github/workflows/sync-shared-config.yml

Revert "workflows/sync-shared-config: fix zizmor findings"

---

.github/workflows/actionlint.yml
.github/workflows/stale-issues.yml
.github/workflows/sync-shared-config.yml

This helps with transparency and they get updated by Dependabot.

workflows: use full versions

---

.github/workflows/sync-shared-config.yml

build(deps): bump ruby/setup-ruby from 1.204.0 to 1.205.0

---

.github/workflows/sync-shared-config.yml

build(deps): bump ruby/setup-ruby from 1.205.0 to 1.206.0

---

.github/workflows/sync-shared-config.yml

build(deps): bump ruby/setup-ruby from 1.206.0 to 1.207.0

---

.github/actions/sync/shared-config.rb

Needed after Homebrew/brew#18842.

sync/shared-config: fix a RuboCop offense

---

.github/workflows/actionlint.yml

build(deps): bump actions/upload-artifact in the artifacts group

---

.github/workflows/actionlint.yml
.github/workflows/sync-shared-config.yml

Doing the usual in this repo so that secrets can be accessed.

dependabot: 2025.03.21 update

---

.github/workflows/sync-shared-config.yml

workflows/sync-shared-config: fix further Dependabot issues

---

.github/actions/sync/shared-config.rb

This should make it clearer that they are synced and should be changed here instead.

sync/shared-config: add caveats for more YAML files.

---

.github/actions/sync/shared-config.rb
.github/dependabot.yml

We need to ensure we don't "sync" the original templates with their slimmed down or modified versions.

Restore templates.

---

.github/dependabot.yml

- Use a single group for all updates
- Add semver cooldowns to all updates

Use new Dependabot functionality

---

.github/dependabot.yml

I think this is now the correct syntax.

github/dependabot: fix groups syntax.

---

.github/actions/sync/shared-config.rb

Don't want/need to do this for Homebrew/brew.

sync/shared-config: fix updating Gemfile.lock.

---

.github/actions/sync/dependabot.template.yml
.github/actions/sync/shared-config.rb

This is the correct syntax for having a single PR for multiple ecosystems.

Use Dependabot `multi-ecosystem-groups`

---

.github/actions/sync/dependabot.template.yml
.github/dependabot.yml

These are not working as expected and preventing Dependabot PR's from being opened.

dependabot: remove cooldowns
