Homebrew/.github

.github/workflows/sync-triage-config.yml
.github/workflows/triage-issues.yml
actions/sync/triage-config.rb

This PR adds two workflow to the `.github` repository.
The first is the new `triage-issues` workflow that will be used to triage issues for the Homebrew organization. This includes marking issues as stale and locking old issues. This will be a replacement for the existing [stale bot](https://github.com/Homebrew/.github/blob/master/.github/stale.yml) and [lock bot](https://github.com/Homebrew/.github/blob/master/.github/lock.yml) which are both inactive. This has been discussed previously on Slack, in https://github.com/Homebrew/homebrew-core/pull/65631, and https://github.com/Homebrew/brew/pull/9368.
The second is a new `sync-triage-config` workflow. This workflow will sync the changes made to the `triage-issues` workflow in this repo to all of the other repos in the organization that use …

Sync triage-issues workflow among Homebrew repos

---

.github/workflows/sync-triage-config.yml

This PR adds the remaining repositories in the Homebrew organization to the `sync-triage-config` workflow. This means that PRs will automatically be opened in these repos whenever the `triage-issues` workflow is modified here.
A few notes:
- I didn't add `Homebrew/linuxbrew-core` as I think they will get these changes via their regular Homebrew/homebrew-core merges.
- I didn't add `Homebrew/actions` to this list. I think it's the only major repo we have isn't on the list. It doesn't currently have any stale bots or anything set up, but if we'd like to add it I can do so. This may be a question for @jonchang.
- I added the `Homebrew/Homebrew-cask` and `Homebrew/Homebrew-cask-*` repos to this list as well. @Homebrew/cask maintainers, please let me know if you would rather I didn't add these …

sync-triage-config: add organization repos

---

.github/workflows/sync-triage-config.yml

Add `Homebrew/homebrew-formula-analytics` and `Homebrew/rubydoc.brew.sh` to the list of repos to sync.
CC: @MikeMcQuaid

workflows/sync-triage-config: sync more repos

---

.github/dependabot.yml

There have been two new releases of the [lock-threads](https://github.com/dessant/lock-threads) since this was last updated.
I don't know how often we want to update these. I'm partially opening this PR to discuss this. In this particular case, there are two changes:
1. update imported package name (https://github.com/dessant/lock-threads/commit/eba004bec39a410184db347eec5294ca57d38188)
1. update dependencies (https://github.com/dessant/lock-threads/commit/eb0aabb42c66b0d8f954cbceabe5809170095a9a)
Both of these seem legitimate to me, but it also doesn't seem like it fixes any bugs or adds any new features. I think the only concern is whether or not we want to update the version in all repos (which would require merging PRs in all of those).
Because of that, I'm kind of leaning toward …

Add dependabot configuration for GitHub actions

---

.github/workflows/sync-triage-config.yml
.github/workflows/triage-issues.yml

- Use new `HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN` for creating pull requests  as @BrewTestBot
- Use `GITHUB_TOKEN` for locking/closing/commenting (which will change comments from @BrewTestBot to the GitHub Actions bot but is worth the reduction in access permissions and number of repositories that need `HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN`)
Also, while we're here, let my editor autocorrect the YAML formatting.

Adjust token usage

---

.github/workflows/sync-triage-config.yml

Use a new, repo-specific token with workflow write access.

workflows/sync-triage-config: fix token usage.

---

.github/workflows/sync-triage-config.yml

Sign the synchronization commits in PRs opened by the `sync-triage-config` workflow.
The `BREWTESTBOT_GPG_SIGNING_SUBKEY` and `BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE` secrets will need to be added to this repo if they're not already accessible.
CC: @MikeMcQuaid and @Bo98

workflows/sync-triage-config: sign commits

---

.github/workflows/triage-issues.yml

Closes https://github.com/Homebrew/homebrew-core/issues/76763
This PR adds a stale configuration that will handle PRs labeled with `bump-formula-pr` or `bump-cask-pr`. They will be marked stale after 48 hours, and closed after an additional 24 hours. When marked as stale, the following message will be left:
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. To keep this pull request open, add a `help wanted` or `in progress` label.
Right now, this message doesn't reference the `bump-*-pr` label that caused it to be marked as stale earlier than a typical PR. Is that okay? Also, this currently uses the same `stale` label that is used by the regular stale action. I think this is fine because this …

triage-issues: add stale configuration for `bump-*-pr` labels

---

.github/dependabot.yml

See https://github.com/Homebrew/brew/issues/11401
There's no reason to limit this to `weekly` when each repo will check `daily`

dependabot: change update interval to "daily"

---

.github/workflows/sync-triage-config.yml

Sync the Homebrew/homebrew-json repo

sync-triage-config: add Homebrew/homebrew-json to synced repos

---

.github/workflows/sync-triage-config.yml

`Homebrew/homebrew-json` has been removed so let's not try to sync `triage-issues.yml` to it anymore.

Don't try to sync the triage-issues workflow with Homebrew/homebrew-json

---

.github/workflows/triage-issues.yml

`actions/stale` supports settings close issue reason since [v5.1.0](https://github.com/actions/stale/releases/tag/v5.1.0). I suggest marking such issues as ["not planned"](https://github.blog/changelog/2022-03-10-the-new-github-issues-march-10th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons) to distinguish them in UI easily.

triage-issues: close issues/PRs as "not planned"

---

SECURITY.md

- This info was on HackerOne and we're moving towards having everything in GitHub. Let's add all the policy wording we had there in here so that researchers can find it more easily and know what is (not) in scope.
- Related PR: https://github.com/Homebrew/brew/pull/14132.

SECURITY: Copy and augment policy that we had on HackerOne

---

.github/workflows/sync-triage-config.yml
.github/workflows/triage-issues.yml

* [workflows/sync-triage-config: remove deprecated repos](https://github.com/Homebrew/.github/commit/a3ec1bd88aaec3cfce59bfdf662db3042f4ec153)
- Remove Homebrew/gsoc (archived)
- Remove Homebrew/homebrew-cask-drivers (archived soon, probably). Current maintainers are been rejecting these PRs anyway.
- Don't fail fast as we want to sync to as many repos as possible, and ideally not cut off any between push and PR creation.
* [workflows/triage-issues: don't check discussions](https://github.com/Homebrew/.github/commit/76b1acbef83cb5f6ace944f0efd96e0d5e971693)
- Adapt for breaking v5 change: #88
- This didn't actually matter in terms of locking behaviour since we don't sync to Homebrew/discussions, but search API rate limits are at a premium and it's worth saving on those where possible.

Fixes for deprecated repos etc.

---

SECURITY.md

Per Slack discussion: researchers are sometimes tempted to submit public PRs containing pentesting/partially proven-out exploits. We should discourage that explicitly.
(Language is not settled here, please aggressively nitpick!)
CC @p-linnane @Bo98

SECURITY: make conduct section, warn against weaponized PRs

---

.github/workflows/lock-threads.yml
.github/workflows/stale-issues.yml

Some of the repositories are starting to [hit GitHub rate limits due to running the tasks sequentially](https://github.com/Homebrew/homebrew-bundle/actions/runs/8515410691).
These aren't that time sensitive so instead, we can split them into multiple jobs that run an hour apart.

split locking threads and stale issue cleanup

---

.github/actions/sync/triage-config.rb

Companion to #97. This makes sure the renamed workflows are properly synced to Homebrew repos.

triage-config.rb: update workflows to sync

---

.github/actions/sync/triage-config.rb

I think we need to retain the old `triage-issue` path to ensure it is removed from the other repos. Unless we manually remove it.
CC: @MikeMcQuaid

triage-config: keep old path

---

.github/actions/sync/triage-config.rb
.github/workflows/sync-triage-config.yml

Reverts #100
The workflow has been synced to all repos, so it's safe to remove it from the list now.
Also, remove Homebrew/homebrew-autoupdate from the list of repos to sync as the tap is no longer official.

Revert "triage-config: keep old path"

---

.github/workflows/sync-shared-config.yml

Found another repo that needs added.

workflows/sync-shared-config: add mass-bottling-tracker.

---

.github/workflows/sync-shared-config.yml

Revert "workflows/sync-shared-config: add mass-bottling-tracker."

---

.github/actions/sync/shared-config.rb
.github/workflows/sync-shared-config.yml
.rubocop.yml

- Improve code style to match `brew style` norms.
- General code refactoring/cleanup.
- Fail script on invalid parameters.
- Provide custom handling for `.rubocop.yml` and `.ruby-version` from Homebrew/brew's repository. We want to match the RuboCop and (Portable) Ruby version (without revision) usage from there.
- Ensure that this workflow is always tested (but PRs not created) when triggered by a pull request.
- Check code style with `brew style` in CI.

Improve shared configuration syncing.

---

.github/actions/sync/shared-config.rb
.github/workflows/sync-shared-config.yml

- Use different source file from Homebrew/brew.
- Reject lines that don't make sense.
- Install and use the appropriate Ruby version.

sync/shared-config: tweak rubocop.

---

.github/actions/sync/shared-config.rb
.github/dependabot.yml

- Also sync a decent, default, comprehensive Dependabot configuration
- Allow opt-out for custom RuboCop and Dependabot configurations

Further improve shared configuration syncing

---

.github/actions/sync/shared-config.rb

We want to use grouped updates here

sync/shared-config: mark ci-orchestrator as a custom Dependabot config

---

.github/workflows/sync-shared-config.yml

Run every 3 hours and allow concurrent runs of pushed branches.

workflows/sync-shared-config: run on a schedule.

---

.github/actions/sync/shared-config.rb

This will avoid issues with `#!/usr/bin/env ruby` shebangs in Homebrew's prefix.
See also https://github.com/Homebrew/brew/pull/17441

sync/shared-config: move brew's ruby version to Library/Homebrew.

---

.github/actions/sync/shared-config.rb
.github/workflows/sync-shared-config.yml

- the docs syncing should allow us to enforce a consistent structure for documentation across all our repositories.
- the dependabot syncing changes should avoid red CI and unnecessary dependabot checks in repositories missing the relevant files.
While we're here:
- use `yaml` consistently instead of `yml`

sync/shared-config: sync docs, improve dependabot.

---

.github/actions/sync/shared-config.rb
.github/dependabot.yml

Need to ensure that this repository contains the superset of all required values for all other repositories in the Homebrew GitHub organisation so that filtering works as expected.

Fix dependabot.yml handling

---

.github/actions/sync/shared-config.rb

- also sync `.vale.ini` file
- don't sync `ruby-macho` docs, as they are not a Jekyll site

actions/sync: more docs tweaks.

---

.github/actions/sync/shared-config.rb

Some directory names were being incorrectly omitted.

actions/sync: fix docs subpaths.

---

.github/workflows/sync-shared-config.yml

We're trying to filter this out for e.g. RubyGems so let's not use it in the workflow.

workflows/sync-shared-config: don't use `vendor` in path.

---

.github/actions/sync/shared-config.rb

This avoids the need to manually update this file in every repository.

actions/sync/shared-config: update Gemfile.lock if it exists.

---

.github/actions/sync/shared-config.rb

This should take less time than `bundle install`, apparently.

actions/sync/shared-config: cheaper bundler run.

---

.github/actions/sync/shared-config.rb

Ensure that we're only going to do this in cases where we actually know that we have the correct Ruby version.

actions/sync/shared-config: don't run bundle for custom rubies.

---

.github/actions/sync/shared-config.rb
.github/workflows/sync-shared-config.yml

- Use `exclude?` instead of `include?` to make RuboCop happy
- Properly check the `sync` jobs success so that auto-merge is not run if jobs are failing

sync-shared-config: fix style and style checks.

---

.github/actions/sync/shared-config.rb

I suggested a Bundler update in a previous PR and didn't really think my suggestion through properly. Right now it's eagerly getting the latest version which will have PR churn every week or two.
Instead, align it with the version used in the Homebrew/brew lock file, just like how we align Ruby to Homebrew/brew's Ruby version.

actions/sync/shared-config: align Bundler version with Homebrew/brew

---

.github/workflows/sync-shared-config.yml

Currently, the `bundle update --ruby` is incorrectly synced on Homebrew/.github's `.ruby-version` rather than Homebrew/brew's.
This is because the flow goes like this:
* .ruby-version on .github is 3.3.2
* setup-ruby installs 3.3.2
* sync script run under 3.3.2
* 3.3.3 copied from Homebrew/brew to repo
* bundler install --ruby called but the ruby installed is still 3.3.2 as we didn't run setup-ruby again
* update to lockfile doesn't happen (until after the .ruby-version update PR is merged in Homebrew/.github)
This fixes it by doing an initial pre-sync of the ruby version _prior_ to starting the sync script. Bundler will then operate under that new Ruby.

Pre-sync initial Ruby version

---

.github/actions/sync/shared-config.rb

If there's one of these files in the repository root: we don't also need one in the `docs` directory.
While we're here, also DRY up some `Gemfile.lock` variable usage.

sync/shared-config: avoid syncing multiple Gemfile*, .ruby-version.

---

.github/actions/sync/shared-config.rb

The previous implementation was not working as expected.

actions/sync/shared-config: fix relative symlinks.

---

.github/workflows/stale-issues.yml
.github/workflows/sync-shared-config.yml

Pin the version of the actions to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

workflows: pin actions

---

.github/workflows/sync-shared-config.yml

Use `gh pr create` to create PRs instead of
`peter-evans/create-pull-request` because the trust model for using `gh` is nicer.

sync-shared-config: use `gh pr create` to create PRs

---

.github/workflows/sync-shared-config.yml

Need to use the full version, not my local alias 🤦🏻

workflows/sync-shared-config: fix `git` command.

---

.github/workflows/sync-shared-config.yml

This avoids trying to run a command in backticks.

workflows/sync-shared-config: fix quotes.

---

.github/workflows/sync-shared-config.yml

This is done already by `shared-config.rb`.

workflows/sync-shared-config: no `git commit` needed.

---

.github/workflows/sync-shared-config.yml

Also, while we're here, add a nicer link to the workflow.

workflows/sync-shared-config: fix `--body` argument to `gh pr create`.

---

.github/workflows/sync-shared-config.yml

This should fix another error.

workflows/sync-shared-config: use `--head` to specify the PR branch.

---

.github/workflows/sync-shared-config.yml

workflows/sync-shared-config: only create PR if needed.

---

.github/actions/sync/shared-config.rb

Rather than just not managing these: let's actually delete them all.

sync/shared-config: remove locked threads workflows.

---

.github/actions/sync/shared-config.rb

Needed to remove the destination not target path here.

sync/shared-config: remove locked threads file correctly.

---

.github/workflows/sync-shared-config.yml

`gh` only recognises `GH_TOKEN`.

workflows/sync-shared-config: fix PR creation (again)

---

.github/workflows/sync-shared-config.yml

`gh pr view` does not work well when there are multiple PRs associated with the same branch. Let's rely on the API instead.

workflows/sync-shared-config: fix check for open PR

---

.github/workflows/sync-shared-config.yml

Hopefully the final fix. `gh pr create` seems to require that the branch exist in remote.

workflows/sync-shared-config: fix PR creation

---

.github/workflows/sync-shared-config.yml

When we update a branch, force push with lease fails. While we can do a `git fetch`, there's no harm to just force push.

workflows/sync-shared-config: force push to branch (without lease)

---

.github/workflows/sync-shared-config.yml

No need to update the branch if there are no changes.

workflows/sync-shared-config: only force push if there are changes

---

.github/workflows/stale-issues.yml

The `contents` permission needs to be set to `write` [^1].
Fixes https://github.com/Homebrew/homebrew-core/actions/runs/10311349943/job/28544771394#step:2:722.
[^1]: https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#delete-a-reference

workflows/stale-issues: fix branch deletion

---

.github/actions/sync/shared-config.rb

This needs the path fixed up so it's not the same as Homebrew/brew.

actions/sync/shared-config: fix docs/.rubocop.yml syncing.

---

.github/actions/sync/shared-config.rb

- filter out unnecessary cops from the docs rubocop config
- add a comment to the synced docs rubocop config file

actions/sync/shared-config: further improve docs rubocop sync.

---

.github/actions/sync/shared-config.rb

This will avoid trying to check gems in the vendor directory.

actions/sync/shared-config: exclude vendor from docs RuboCop.

---

.github/actions/sync/shared-config.rb

This should be in the general rubocop, not the docs one.

actions/sync/shared-config: fix vendor exclude.

---

.github/actions/sync/shared-config.rb

Oh please just let this work properly already.

actions/sync/shared-config: use a wider vendor wildcard.

---

.github/actions/sync/shared-config.rb
.github/workflows/actionlint.yml
.github/workflows/sync-shared-config.yml

This makes sure we run `actionlint` and `zizmor` across all our repos.

Add and sync actionlint workflow

---

.github/workflows/actionlint.yml

Most of our repos still use a `master` branch as default.

workflows/actionlint: run on push to `master` too

---

.github/workflows/actionlint.yml

- Rename the workflow to `Actionlint` to match the file name.
- Persist credentials, but only on private repositories, because
checking out the repo seems to fail on private repositories without
doing this.
- Upload the SARIF file only on public repositories, since this feature
is not available on private repositories.

workflows/actionlint: various fixes

---

.github/workflows/actionlint.yml

It should be `github.event.repository.private`, not
`github.repository.private`.

workflows/actionlint: fix actionlint error

---

.github/workflows/actionlint.yml

We don't need this on private repositories, apparently.

workflows/actionlint: avoid persisting credentials

---

.github/workflows/actionlint.yml

We currently run only when when workflow files are modified, but that
means we cannot make the results of the Zizmor scan a required status
check.
Let's just run this all the time so that we can make sure to never merge
regressions.
This will affect only one high-volume repo: Homebrew/cask. We can carve
out an exception for that if we need to. (Though I'm currently inclined
to do something similar on our high-volume repos anyway.)
See discussion at Homebrew/ci-orchestrator#255

actionlint: run on every push

---

.github/workflows/sync-shared-config.yml

This has the same effect as #214, but in the opposite direction: it suppresses the error by making it clear that we're intending to persist credentials.

 sync-shared-config.yml: explicit persistence of credentials

---

.github/workflows/actionlint.yml

`zizmor` no longer exits with an error when passed `--format sarif`.

actionlint: stop suppressing `zizmor` exit code

---

.github/workflows/sync-shared-config.yml

We're getting so many of these PRs now and we don't need this much syncing/noise when we can do it less often or manually with a `workflow_dispatch` if needed.

workflows/sync-shared-config: run weekly.

---

.github/workflows/actionlint.yml

This should allow us to make use of the GitHub merge queue to ensure that we're not merging outdated code (or breaking `master`) but avoiding the need to continually merge into/rebase PR branches.
This should be safe to merge as-is as is essentially a no-op without the merge queue enabled.

workflows/actionlint: enable merge queue/group jobs.

---

.github/workflows/sync-shared-config.yml

https://github.com/Homebrew/.github/pull/221 from a non-fork.

build(deps): bump ruby/setup-ruby from 1.202.0 to 1.203.0

---

.github/workflows/sync-shared-config.yml

https://github.com/Homebrew/.github/pull/228 from a non-fork.

build(deps): bump ruby/setup-ruby from 1.203.0 to 1.204.0

---

.github/workflows/actionlint.yml

build(deps): bump github/codeql-action from 3.27.9 to 3.28.0

---

.github/dependabot.yml
.github/workflows/sync-shared-config.yml

This should reduce the amount of PR spam we get.
If there's critical vulnerabilities: they will be updated more often or can be done manually with a workflow dispatch.

Update dependabot actions and scheduled files weekly.

---

.github/workflows/sync-shared-config.yml

https://github.com/Homebrew/.github/pull/243 from a non-fork.

build(deps): bump ruby/setup-ruby from 1.207.0 to 1.208.0

---

.github/workflows/actionlint.yml

This addresses https://github.com/advisories/GHSA-vqf5-2xx6-9wfm.
That vulnerability has no direct impact on us since we're not doing Java/Kotlin scanning, but there's also no reason to keep it on our radar.
Detected with `zizmor`:
```
error[known-vulnerable-actions]: action has a known vulnerability
--> .github/workflows/actionlint.yml:82:9
|
82 |         uses: github/codeql-action/upload-sarif@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c # v3.28.1
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ GHSA-vqf5-2xx6-9wfm
|
= note: audit confidence → High
```

actionlint: bump upload-sarif to v3.28.5

---

.github/workflows/actionlint.yml

build(deps): bump github/codeql-action from 3.28.9 to 3.28.10

---

.github/workflows/actionlint.yml
.github/workflows/sync-shared-config.yml

build(deps): bump github/codeql-action from 3.28.10 to 3.28.11

---

.github/workflows/sync-shared-config.yml

#264 from a non-fork. Closes #264.

build(deps): bump ruby/setup-ruby from 1.222.0 to 1.226.0

---

.github/dependabot.yml
.github/workflows/sync-shared-config.yml

- Update Dependabot once a week on Monday at 8AM (for new releases)
- Update sync-shared-config once a week on Thursday at 8AM (for after Dependabot has hopefully been mostly merged/updated)
- Update repository list based on the latest, non-deprecated repositories

Improve sync schedules

---

.github/dependabot.yml

Dependabot does not allow the use of `cron` for setting schedules.
Update to use the required syntax.
It looks like because dependabot is not enabled on this repo, the changes don't get verified, where they do in the downstream syncs - see https://github.com/Homebrew/homebrew-cask/pull/205774

dependabot: fix schedules

---

.github/workflows/sync-shared-config.yml

Now that we've removed all the GPG code, this is a no-op.

workflows: remove no-op ssh signing value

---

.github/workflows/actionlint.yml

From what I can see we aren't able to upload the SARIF record within the merge group because it can't find a ref to upload against.
This was seen in `homebrew/cask` - https://github.com/Homebrew/homebrew-cask/actions/runs/14210386041/job/39816439146
As far as I can see, no other repositories that this file is synced to have merge queue enabled, so the failure hasn't been seen until now.
To turn on the merge queue for `homebrew/cask` this trigger was disabled, but it's being brought back with the sync job in https://github.com/Homebrew/homebrew-cask/pull/207413
---
An alternative may be to skip the upload job, and only run the `actionlint` side of the workflow when it is a merge_group, unless there is an alternative way to link to a ref.
---
CC: @MikeMcQuaid because you turned it on in …

workflows/actionlint: don't trigger on merge_group

---

.github/actions/sync/shared-config.rb
.github/workflows/sync-shared-config.yml

The scheduled run has been in bad health for some time: https://github.com/Homebrew/.github/actions/workflows/sync-shared-config.yml?query=event%3Aschedule
* Support Dependabot PRs better so we (hopefully) don't need to do manual work to merge them anymore.
- Private repos aren't tested anymore in Dependabot PRs but that's probably fine - they'll still sync on schedule like the rest and the only thing about private repos that Dependabot could really break is `actions/checkout` token handling - but that would be a major bug on GitHub's side.
* Fix workflow erroring when no changes need to be made
* Handle RuboCop plugins properly (we previously stripped `require` but weren't stripping `plugins`)
* Remove `orka_api_client` handling, which I've deprecated

Fix various syncing errors

---

.github/actions/sync/shared-config.rb
.github/zizmor.yml

This is internally owned so we don't really gain much security benefits here.
Should fix some security alerts that popped up in the last couple days. I'll follow up with the CodeQL ones since for some reason they are substantially more complex to configure.

Configure zizmor to allow `Homebrew/actions/*` to point to `master`

---

.github/workflows/sync-shared-config.yml

This follows on from the Homebrew/brew dependabot sync on Friday in https://github.com/Homebrew/brew/pull/19991

workflows/sync-shared-config: change sync to every Tuesday.

---

.github/actions/sync/shared-config.rb
.github/dependabot.yml

After trying this out in Homebrew/brew, let's adopt a similar approach on all other repositories:
- make Homebrew/brew and Homebrew/ci-orchestrator consistent with this repository for now to try things out
- do updates weekly rather than daily. GitHub will still push out urgent security updates ad-hoc.
- do all updates on Friday at 08:00 UTC to allow syncing earlier in the week from this repository and then later in the week for dependabot
- use groups for all updates
- use directories to allow grouping updates by repository and handling more repositories with different layouts

Revamp Dependabot configuration.

---

.github/actions/sync/shared-config.rb
.github/codeql/extensions/homebrew-actions.yml

Should fix the hundreds of alerts everywhere.
This aligns with how we have configured zizmor.

Allow unpinned Homebrew actions in CodeQL

---

.github/workflows/actionlint.yml

This was removed accidentally for homebrew-core so let's just do the same thing everywhere.

workflows/actionlint: import homebrew-core logic.

---

.github/workflows/actionlint.yml
.github/workflows/sync-shared-config.yml

We've migrated this repository to a `main` default branch.

github/workflows: use main branch for Homebrew actions.

---

.github/actions/sync/shared-config.rb

We're adding this now when not needed.

sync/shared-config: strip unnecessary YAML newline.

---

.github/workflows/actionlint.yml

This enables additional checks such as `impostor-commit`,
`ref-confusion`, `known-vulnerable-actions`, and others.

actionlint: set `GH_TOKEN` for `zizmor`

---

.github/workflows/actionlint.yml

This will make this job run a bit faster. We didn't run it in a
container previously because it was erroring out for some reason in
Homebrew/core, but it seems to be fine now? See
Homebrew/homebrew-core#229566.

actionlint: run `workflow_syntax` in a container

---

.github/workflows/actionlint.yml

This is needed in order to merge Homebrew/ci-orchestrator#579.

actionlint: run on all PRs

---

.github/dependabot.yml

Devcontainers also don't support semver cooldown.

github/dependabot: fix cooldown syntax (yet again).

---

.github/workflows/sync-shared-config.yml

We are not currently syncing to the user-management repo, which means it's constantly behind on GitHub Actions versions. Also alphabetized the repos.

sync-shared-config: sync to user-management repo

---

.github/actions/sync/dependabot.template.yml
.github/actions/sync/shared-config.rb

Opened https://github.com/Homebrew/brew/pull/20315 in the wrong location, so now trying again in the correct repo.
I've split the commits here for easier review. I alphabetized the ecosystems in each file, and then added Terraform. This is needed for the user-management repo.

dependabot: updates for Terraform

---

.github/workflows/actionlint.yml

`test-bot` has been merged into Homebrew/brew, so this is no longer necessary and outputs a warning in CI.

workflows/actionlint: remove `test-bot` Action input

---

.github/workflows/sync-shared-config.yml

This repository will shortly be archived.

workflows/sync-shared-config: remove homebrew-portable-ruby.
